apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgs-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sgs-app
  template:
    metadata:
      labels:
        app: sgs-app
    spec:
      imagePullSecrets:
        - name: my-dockerhub-secret
      containers:
        - name: sgs-app
          image: skylineglobe/skylineglobeserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5155
          env:
            - name: SGS__ServerConfig__CatalogDBType
              value: SQLite
            - name: SGS__ServerConfig__SharedDataPath
              value: /app/data
            - name: SGS__ServerConfig__PublicUrl
              value: https://sgs.localhost
            - name: SGS__ServerConfig__LicenseServerURL
              value: ""
            - name: SGS__Kestrel__Endpoints__Http__Url
              value: http://0.0.0.0:5155
            - name: SGS__AllowedHosts
              value: "*"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: data-volume
              mountPath: /app/data
	      
            # -----------------------------------------------------
            # Option 1: Mount a subfolder (keeps the original /app/tef/custom contents)                 
            # -----------------------------------------------------
            - name: more-data-volume
              mountPath: /app/tef/custom/more-data
	      
            # -----------------------------------------------------
            # Option 2: Mount a single file (adds/replaces one file).
            # The "readOnly: true" field is the equivalent of ":ro" in Docker.
            # -----------------------------------------------------
            - name: custom-file-volume
              mountPath: /app/tef/custom/my-config.json
              subPath: my-config.json
              readOnly: true          
      volumes:
        - name: config-volume
          hostPath:
            path: "/run/desktop/mnt/host/c/Users/Administrator/Desktop/K8S/https_sqlite/config"
        - name: data-volume
          hostPath:
            path: "/run/desktop/mnt/host/c/Users/Administrator/Desktop/K8S/https_sqlite/data"
	    
        # -----------------------------------------------------
        # Option 1: Host folder to mount as a subfolder inside the container
        # -----------------------------------------------------
        #- name: more-data-volume
        #  hostPath:
        #    path: "/run/desktop/mnt/host/c/Users/Administrator/Desktop/K8S/https_sqlite/more-data"

        # -----------------------------------------------------
        # Option 2: Host file to mount as read-only
        # -----------------------------------------------------
        #- name: custom-file-volume
        #  hostPath:
        #    path: "/run/desktop/mnt/host/c/Users/Administrator/Desktop/K8S/https_sqlite/custom/myconfig.json"
