services:

  skylineglobeserver:
    image: skylineglobe/skylineglobeserver:latest # Docker image to use
    container_name: skylineglobeserver_container
    restart: always 
    ports:
      - "5000:5155" # Map container port to host. Adjust according to your app's exposed port
    environment:   # Configure SGS
      SGS__ServerConfig__CatalogDBType: SQLite
      SGS__ServerConfig__SharedDataPath: /app/data/SkylineGlobeServerConfiguration    
      SGS__ServerConfig__PublicUrl: http://localhost:5000
      SGS__ServerConfig__LicenseServerURL: ""
    volumes:  # Mount local folders for data persistence
      - ./data:/app/data 
      - ./config:/app/config 
      # Option 1: Mount a subfolder (keeps the original /app/tef/custom contents)      
      # - ./more-data:/app/tef/custom/more-data
      # Option 2: Mount a single file (adds/replaces one file). ":ro" makes the mount read-only      
      # - ./my-config.json:/app/tef/custom/my-config.json:ro
    networks:
      - skyline_network

networks:
  skyline_network:
    driver: bridge
